# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginxinc/nginx-prometheus-exporter"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_darwin_amd64.tar.gz"
      sha256 "c2d4c7e85b519d78e987667c84bce7697d7e19ed8a4a07b14c17538bd6339145"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    on_arm do
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_darwin_arm64.tar.gz"
      sha256 "d89fd61eabcf3a04622493feca41b7f2d3b89669d84c213ad15ad433bcdb5a80"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz"
        sha256 "4e27d332281e6bda7514f51f5a6e7c62f8bfb7667d459095a4c73d437b2d27ad"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_armv6.tar.gz"
        sha256 "a091f7c24faf6ecf313038715b28ccdd0f252a672050cf9f9fd71f5070935e82"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_arm64.tar.gz"
        sha256 "c78cd780d8f3f659cb3c8655f9491dc5ffe90a9bf60a91fc9829cc5afde318fd"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
  end
end
