# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginxinc/nginx-prometheus-exporter"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_darwin_arm64.tar.gz"
      sha256 "ea949bf48d7fecab7f2aa5d0c8ae080eb446679aa6df60e9313572a7f2930567"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_darwin_amd64.tar.gz"
      sha256 "12d26ebc97cbdb72497a11c8d566329156a810eb6f1068c957c8248e30d8e5f1"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_arm64.tar.gz"
      sha256 "314047c88efdb96d77150646c27c678de7d6441008c5e1f569704db973d1e56e"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz"
      sha256 "fe370b5d93f79a6056dd898d2c7922923de325c75718f9e5b55c3f1998914cb1"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_armv6.tar.gz"
      sha256 "d5f708623200cf37827ed655670f87dbd7fb7ff9aa92ed6344d8583c9fef526b"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end
end
