# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxAsgSync < Formula
  desc "NGINX Plus Integration with Cloud Autoscaling"
  homepage "https://github.com/nginxinc/nginx-asg-sync"
  version "1.0.0"
  license "BSD-2-Clause"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-asg-sync/releases/download/v1.0.0/nginx-asg-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "e9d6dcab1a9f8d173a70cdd1dcbed60088464d0efcf996f38c5b43275cc0cb36"

      def install
        bin.install "nginx-asg-sync"
      end
    end
  end
  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-asg-sync/releases/download/v1.0.0/nginx-asg-sync_1.0.0_linux_arm64.tar.gz"
      sha256 "5f3f2471abaa08de35bd61dea56cc90b3a856b3b9ccaa8d9b0390bf4da407545"

      def install
        bin.install "nginx-asg-sync"
      end
    end
  end
end
