# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginxinc/nginx-prometheus-exporter"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.4.0/nginx-prometheus-exporter_1.4.0_darwin_amd64.tar.gz"
      sha256 "481f88a0170742693b80c14b1f654a389d4df711a2509ce62a8a11f6ad81a296"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    on_arm do
      url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.4.0/nginx-prometheus-exporter_1.4.0_darwin_arm64.tar.gz"
      sha256 "bac08cc42313708ed7c255609cbde964284ee03e68dc4ed04007982badea43f2"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.4.0/nginx-prometheus-exporter_1.4.0_linux_amd64.tar.gz"
        sha256 "b205572ff6a89e4bdfec7519e936f7cc8d1bf1ef133cee26aef4bc4bc4ea4b4a"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.4.0/nginx-prometheus-exporter_1.4.0_linux_armv6.tar.gz"
        sha256 "6df6e2606a5d7c995432064e57fc3aa01807b525476977da14aec6bf89557b9f"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.4.0/nginx-prometheus-exporter_1.4.0_linux_arm64.tar.gz"
        sha256 "ec416e160c8c238ed27e7c27a60fa80a5b5d7848edd70f0165878ab5b9f5fb4a"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
  end
end
