# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxAsgSync < Formula
  desc "NGINX Plus Integration with Cloud Autoscaling"
  homepage "https://github.com/nginxinc/nginx-asg-sync"
  version "1.0.0"
  license "BSD-2-Clause"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-asg-sync/releases/download/v1.0.0/nginx-asg-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "6f4f1156214cef256cf6c8632956dad10129e5f9cfd4b1a4b283ebd87858f059"

      def install
        bin.install "nginx-asg-sync"
      end
    end
  end
  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/nginxinc/nginx-asg-sync/releases/download/v1.0.0/nginx-asg-sync_1.0.0_linux_arm64.tar.gz"
      sha256 "a939c978b8d4a8133c22511ae49cd097ad286da93c3c1875650bd71bf18041e3"

      def install
        bin.install "nginx-asg-sync"
      end
    end
  end
end
